services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ensino_certo
      - DB_USERNAME=ensino_certo_user
      - DB_PASSWORD=senha_segura
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=root_senha_segura
      - MYSQL_DATABASE=ensino_certo
      - MYSQL_USER=ensino_certo_user
      - MYSQL_PASSWORD=senha_segura
    volumes:
      - db_data:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - "3306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root_senha_segura
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: