services:
  app:
    build: .
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
    expose:
      - "80"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=ensino_certo
      - MYSQL_USER=ensino_certo_user
      - MYSQL_PASSWORD=senha_segura
    expose:
      - "3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root123
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped